stimulibasedir2 = '/Users/lss/Documents/MATLAB/MakingSenseOfSounds/12610922/Development/Human' ;
n_exp = create_AN_files(stimulibasedir2, experimentname,dirname, '000_allfiles.txt', 0, ...
'bmSigdir', 'ANSigdir_100_16', 'paramfilelocation', stimulibasedir)  ;
stimulibasedir3 = '/Users/lss/Documents/MATLAB/MakingSenseOfSounds/12610922/Development/Music' ;
n_exp = create_AN_files(stimulibasedir3, experimentname,dirname, '000_allfiles.txt', 0, ...
'bmSigdir', 'ANSigdir_100_16', 'paramfilelocation', stimulibasedir)  ;
stimulibasedir4 = '/Users/lss/Documents/MATLAB/MakingSenseOfSounds/12610922/Development/Nature' ;
n_exp = create_AN_files(stimulibasedir4, experimentname,dirname, '000_allfiles.txt', 0, ...
'bmSigdir', 'ANSigdir_100_16', 'paramfilelocation', stimulibasedir)  ;
stimulibasedir5 = '/Users/lss/Documents/MATLAB/MakingSenseOfSounds/12610922/Development/Urban' ;
n_exp = create_AN_files(stimulibasedir5, experimentname,dirname, '000_allfiles.txt', 0, ...
'bmSigdir', 'ANSigdir_100_16', 'paramfilelocation', stimulibasedir)  ;